function ClCd = importfile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  OUT = IMPORTFILE(FILENAME) reads data from text file FILENAME for the
%  default selection.  Returns the data as a table.
%
%  OUT = IMPORTFILE(FILE, DATALINES) reads data for the specified row
%  interval(s) of text file FILENAME. Specify DATALINES as a positive
%  scalar integer or a N-by-2 array of positive scalar integers for
%  dis-contiguous row intervals.
%
%  Example:
%  out = importfile("C:\Users\olive\University of Bristol\grp-Optimisation Bois - Documents\General\Code\Aero\AVL\out.txt", [24, 25]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 04-Feb-2022 16:31:41

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [24, 25];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 4);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = "=";

% Specify column names and types
opts.VariableNames = ["Var1", "VarName2", "Var3", "Var4"];
opts.SelectedVariableNames = "VarName2";
opts.VariableTypes = ["string", "string", "string", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Var1", "VarName2", "Var3", "Var4"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var1", "VarName2", "Var3", "Var4"], "EmptyFieldRule", "auto");

% Import the data
ClCd = str2double(table2array(readtable(filename, opts)));

end